import { Competition, Winner } from './types';

// Helper to calculate date
const addDays = (days: number) => new Date(Date.now() + 86400000 * days).toISOString();
const subDays = (days: number) => new Date(Date.now() - 86400000 * days).toISOString();

export const competitions: Competition[] = [
  // --- PRAMS (6 items) ---
  {
    id: 'p1',
    slug: 'bugaboo-fox-5',
    title: 'Bugaboo Fox 5 Bundle',
    description: 'The ultimate all-terrain stroller including carrycot and accessories.',
    image: 'https://images.unsplash.com/photo-1519689680058-324335c77eba?auto=format&fit=crop&q=80&w=1000',
    retailValueGBP: 1450,
    ticketPriceGBP: 1.99,
    maxTickets: 999,
    ticketsSold: 850,
    drawDateTime: addDays(1),
    category: 'Prams',
    status: 'ending_soon',
    bundles: [{ quantity: 1, price: 1.99 }, { quantity: 5, price: 8.99 }]
  },
  {
    id: 'p2',
    slug: 'silver-cross-wave',
    title: 'Silver Cross Wave Double',
    description: 'The ultimate tandem pram system. Converts from single to double in seconds.',
    image: 'https://images.unsplash.com/photo-1504432842672-1a79f78e4084?auto=format&fit=crop&q=80&w=1000',
    retailValueGBP: 1595,
    ticketPriceGBP: 2.49,
    maxTickets: 1000,
    ticketsSold: 400,
    drawDateTime: addDays(5),
    category: 'Prams',
    status: 'active',
    bundles: [{ quantity: 1, price: 2.49 }, { quantity: 5, price: 10.99 }]
  },
  {
    id: 'p3',
    slug: 'uppababy-vista-v3',
    title: 'UPPAbaby Vista V3',
    description: 'Premium convertible stroller with bassinet, toddler seat and accessories.',
    image: 'https://images.unsplash.com/photo-1591085686350-798c0f9faa7f?auto=format&fit=crop&q=80&w=1000',
    retailValueGBP: 1299,
    ticketPriceGBP: 1.79,
    maxTickets: 900,
    ticketsSold: 100,
    drawDateTime: addDays(8),
    category: 'Prams',
    status: 'new',
    bundles: [{ quantity: 1, price: 1.79 }, { quantity: 5, price: 7.99 }]
  },
  {
    id: 'p4',
    slug: 'icandy-peach-7',
    title: 'iCandy Peach 7 Complete',
    description: 'British-designed luxury pushchair with all accessories included.',
    image: 'https://images.unsplash.com/photo-1566576721346-d4a3b4eaeb55?auto=format&fit=crop&q=80&w=1000',
    retailValueGBP: 1599,
    ticketPriceGBP: 2.29,
    maxTickets: 1000,
    ticketsSold: 750,
    drawDateTime: addDays(2),
    category: 'Prams',
    status: 'ending_soon',
    bundles: [{ quantity: 1, price: 2.29 }, { quantity: 5, price: 9.99 }]
  },
  {
    id: 'p5',
    slug: 'cybex-priam',
    title: 'Cybex Priam 4 Rose Gold',
    description: 'Stunning rose gold frame with all-terrain wheels and lux seat.',
    image: 'https://images.unsplash.com/photo-1544543941-35c1b4d7b2d8?auto=format&fit=crop&q=80&w=1000',
    retailValueGBP: 1400,
    ticketPriceGBP: 1.99,
    maxTickets: 800,
    ticketsSold: 200,
    drawDateTime: addDays(6),
    category: 'Prams',
    status: 'active',
    bundles: [{ quantity: 1, price: 1.99 }, { quantity: 5, price: 8.99 }]
  },
  {
    id: 'p6',
    slug: 'joie-signature',
    title: 'Joie Signature Travel System',
    description: 'Complete travel system with i-Size car seat and ISOFIX base.',
    image: 'https://images.unsplash.com/photo-1544543941-d9c2a3e51f82?auto=format&fit=crop&q=80&w=1000',
    retailValueGBP: 899,
    ticketPriceGBP: 1.29,
    maxTickets: 700,
    ticketsSold: 50,
    drawDateTime: addDays(10),
    category: 'Prams',
    status: 'new',
    instantWin: true,
    bundles: [{ quantity: 1, price: 1.29 }, { quantity: 5, price: 5.49 }]
  },

  // --- NURSERY (6 items) ---
  {
    id: 'n1',
    slug: 'snoo-bassinet',
    title: 'SNOO Smart Sleeper',
    description: 'Adds hours of sleep for your baby - and you! The world\'s smartest baby bed.',
    image: 'https://images.unsplash.com/photo-1596870230751-ebdfce98ec42?auto=format&fit=crop&q=80&w=1000',
    retailValueGBP: 1195,
    ticketPriceGBP: 1.49,
    maxTickets: 1000,
    ticketsSold: 200,
    drawDateTime: addDays(7),
    category: 'Nursery',
    status: 'active',
    bundles: [{ quantity: 1, price: 1.49 }, { quantity: 5, price: 6.99 }]
  },
  {
    id: 'n2',
    slug: 'stokke-tripp-trapp',
    title: 'Stokke Tripp Trapp Trio',
    description: 'Three chairs for life. Includes baby set and cushions. Pick your colours!',
    image: 'https://images.unsplash.com/photo-1544243642-4f014e3049b7?auto=format&fit=crop&q=80&w=1000',
    retailValueGBP: 750,
    ticketPriceGBP: 0.99,
    maxTickets: 800,
    ticketsSold: 100,
    drawDateTime: addDays(6),
    category: 'Nursery',
    status: 'new',
    bundles: [{ quantity: 1, price: 0.99 }, { quantity: 10, price: 8.99 }]
  },
  {
    id: 'n3',
    slug: 'o-baby-furniture',
    title: 'Obaby Stamford Furniture Set',
    description: 'Sleigh cot bed, changing unit and wardrobe in white.',
    image: 'https://images.unsplash.com/photo-1522771753035-4a50097a6f55?auto=format&fit=crop&q=80&w=1000',
    retailValueGBP: 1200,
    ticketPriceGBP: 1.25,
    maxTickets: 1200,
    ticketsSold: 600,
    drawDateTime: addDays(3),
    category: 'Nursery',
    status: 'active',
    bundles: [{ quantity: 1, price: 1.25 }, { quantity: 5, price: 5.00 }]
  },
  {
    id: 'n4',
    slug: 'elvie-pump-bundle',
    title: 'Elvie Stride Double Pump',
    description: 'Hospital grade performance, hands-free design. Includes storage bags.',
    image: 'https://images.unsplash.com/photo-1614856050518-e3c314959db4?auto=format&fit=crop&q=80&w=1000',
    retailValueGBP: 350,
    ticketPriceGBP: 0.49,
    maxTickets: 800,
    ticketsSold: 750,
    drawDateTime: addDays(0.2),
    category: 'Nursery',
    status: 'ending_soon',
    bundles: [{ quantity: 1, price: 0.49 }, { quantity: 10, price: 3.99 }]
  },
  {
    id: 'n5',
    slug: 'nursery-makeover',
    title: 'Complete Nursery Makeover',
    description: '£3,000 to spend at Mamas & Papas plus a professional decorator for 2 days.',
    image: 'https://images.unsplash.com/photo-1525956180549-4d511fd16f35?auto=format&fit=crop&q=80&w=1000',
    retailValueGBP: 3500,
    ticketPriceGBP: 2.99,
    maxTickets: 1500,
    ticketsSold: 100,
    drawDateTime: addDays(10),
    category: 'Nursery',
    status: 'new',
    bundles: [{ quantity: 1, price: 2.99 }, { quantity: 5, price: 12.99 }]
  },
  {
    id: 'n6',
    slug: 'baby-monitor-nanit',
    title: 'Nanit Pro Camera Bundle',
    description: 'Smart HD baby monitor with breathing wear and sleep tracking.',
    image: 'https://images.unsplash.com/photo-1555252333-9f8e92e65df9?auto=format&fit=crop&q=80&w=1000',
    retailValueGBP: 399,
    ticketPriceGBP: 0.79,
    maxTickets: 600,
    ticketsSold: 300,
    drawDateTime: addDays(4),
    category: 'Nursery',
    status: 'active',
    instantWin: true,
    bundles: [{ quantity: 1, price: 0.79 }, { quantity: 10, price: 6.99 }]
  },

  // --- TOYS (6 items) ---
  {
    id: 't1',
    slug: 'lego-collection',
    title: 'Ultimate LEGO Bundle',
    description: 'Harry Potter Castle, Star Wars Falcon, and Disney Castle. Hours of building fun.',
    image: 'https://images.unsplash.com/photo-1585366119957-e9730b6d0f60?auto=format&fit=crop&q=80&w=1000',
    retailValueGBP: 1200,
    ticketPriceGBP: 1.50,
    maxTickets: 900,
    ticketsSold: 880,
    drawDateTime: addDays(0.3),
    category: 'Toys',
    status: 'ending_soon',
    bundles: [{ quantity: 1, price: 1.50 }, { quantity: 5, price: 6.00 }]
  },
  {
    id: 't2',
    slug: 'ps5-bundle',
    title: 'PlayStation 5 + 5 Games',
    description: 'For the older kids (and dads!). Includes extra controller.',
    image: 'https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?auto=format&fit=crop&q=80&w=1000',
    retailValueGBP: 650,
    ticketPriceGBP: 0.99,
    maxTickets: 800,
    ticketsSold: 100,
    drawDateTime: addDays(5),
    category: 'Toys',
    status: 'active',
    bundles: [{ quantity: 1, price: 0.99 }, { quantity: 10, price: 8.99 }]
  },
  {
    id: 't3',
    slug: 'electric-ride-on',
    title: 'Mercedes G-Wagon Ride On',
    description: '24V 2-seater electric car for kids with remote control for parents.',
    image: 'https://images.unsplash.com/photo-1549497558-8671404c0df6?auto=format&fit=crop&q=80&w=1000',
    retailValueGBP: 450,
    ticketPriceGBP: 0.49,
    maxTickets: 1000,
    ticketsSold: 200,
    drawDateTime: addDays(4),
    category: 'Toys',
    status: 'active',
    bundles: [{ quantity: 1, price: 0.49 }, { quantity: 10, price: 3.99 }]
  },
  {
    id: 't4',
    slug: 'tonies-bundle',
    title: 'Tonies Box + 10 Characters',
    description: 'Screen-free storytelling. Includes starter set and 10 figures of your choice.',
    image: 'https://images.unsplash.com/photo-1558060370-d644479cb6f7?auto=format&fit=crop&q=80&w=1000',
    retailValueGBP: 250,
    ticketPriceGBP: 0.29,
    maxTickets: 1000,
    ticketsSold: 50,
    drawDateTime: addDays(7),
    category: 'Toys',
    status: 'new',
    bundles: [{ quantity: 1, price: 0.29 }, { quantity: 20, price: 5.00 }]
  },
  {
    id: 't5',
    slug: 'ipad-kids',
    title: '2x iPad Air + Rugged Cases',
    description: 'Perfect for travel and education. 256GB WiFi models.',
    image: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&q=80&w=1000',
    retailValueGBP: 1400,
    ticketPriceGBP: 1.99,
    maxTickets: 800,
    ticketsSold: 600,
    drawDateTime: addDays(2),
    category: 'Toys',
    status: 'active',
    bundles: [{ quantity: 1, price: 1.99 }, { quantity: 5, price: 8.99 }]
  },
  {
    id: 't6',
    slug: 'wooden-climbing',
    title: 'Indoor Wooden Climbing Frame',
    description: 'Montessori style indoor gym with slide and swing.',
    image: 'https://images.unsplash.com/photo-1596464716127-f2a82984de30?auto=format&fit=crop&q=80&w=1000',
    retailValueGBP: 400,
    ticketPriceGBP: 0.59,
    maxTickets: 600,
    ticketsSold: 20,
    drawDateTime: addDays(8),
    category: 'Toys',
    status: 'new',
    bundles: [{ quantity: 1, price: 0.59 }, { quantity: 10, price: 4.99 }]
  },

  // --- HOLIDAYS (6 items) ---
  {
    id: 'h1',
    slug: 'disney-florida',
    title: '14-Night Disney World Florida',
    description: 'Flights, Villa, Car Hire and Park Tickets for a family of 4.',
    image: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&q=80&w=1000',
    retailValueGBP: 8500,
    ticketPriceGBP: 4.99,
    maxTickets: 3000,
    ticketsSold: 1500,
    drawDateTime: addDays(14),
    category: 'Holidays',
    status: 'active',
    bundles: [{ quantity: 1, price: 4.99 }, { quantity: 3, price: 12.00 }]
  },
  {
    id: 'h2',
    slug: 'center-parcs',
    title: 'Center Parcs Executive Lodge',
    description: 'Mid-week or Weekend break at any UK location + £500 spending money.',
    image: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&q=80&w=1000',
    retailValueGBP: 1500,
    ticketPriceGBP: 1.49,
    maxTickets: 1200,
    ticketsSold: 1100,
    drawDateTime: addDays(1),
    category: 'Holidays',
    status: 'ending_soon',
    bundles: [{ quantity: 1, price: 1.49 }, { quantity: 5, price: 6.99 }]
  },
  {
    id: 'h3',
    slug: 'lapland-santa',
    title: 'Lapland Santa Experience',
    description: 'Day trip for 4. Meet the real Santa, husky rides and snowmobiles.',
    image: 'https://images.unsplash.com/photo-1518176258769-e3d8c1c52b0c?auto=format&fit=crop&q=80&w=1000',
    retailValueGBP: 2800,
    ticketPriceGBP: 2.99,
    maxTickets: 1500,
    ticketsSold: 200,
    drawDateTime: addDays(20),
    category: 'Holidays',
    status: 'new',
    bundles: [{ quantity: 1, price: 2.99 }, { quantity: 5, price: 12.00 }]
  },
  {
    id: 'h4',
    slug: 'eurocamp-france',
    title: 'Eurocamp France Holiday',
    description: '7 nights in a Premium Mobile Home. Travel included.',
    image: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&q=80&w=1000',
    retailValueGBP: 1200,
    ticketPriceGBP: 0.99,
    maxTickets: 1000,
    ticketsSold: 400,
    drawDateTime: addDays(6),
    category: 'Holidays',
    status: 'active',
    bundles: [{ quantity: 1, price: 0.99 }, { quantity: 10, price: 8.99 }]
  },
  {
    id: 'h5',
    slug: 'dubai-luxury',
    title: '5* Dubai Family Luxury',
    description: 'Atlantis The Palm. 5 nights half board + waterpark access.',
    image: 'https://images.unsplash.com/photo-1512453979798-5ea904ac6605?auto=format&fit=crop&q=80&w=1000',
    retailValueGBP: 6000,
    ticketPriceGBP: 3.99,
    maxTickets: 2500,
    ticketsSold: 100,
    drawDateTime: addDays(25),
    category: 'Holidays',
    status: 'new',
    bundles: [{ quantity: 1, price: 3.99 }, { quantity: 3, price: 10.00 }]
  },
  {
    id: 'h6',
    slug: 'uk-cottage-stay',
    title: 'Luxury UK Cottage Stay',
    description: 'Dog friendly, hot tub, sleeps 6. Valid for 2 years.',
    image: 'https://images.unsplash.com/photo-1449156493391-d2cfa28e468b?auto=format&fit=crop&q=80&w=1000',
    retailValueGBP: 800,
    ticketPriceGBP: 0.79,
    maxTickets: 1200,
    ticketsSold: 900,
    drawDateTime: addDays(2),
    category: 'Holidays',
    status: 'ending_soon',
    bundles: [{ quantity: 1, price: 0.79 }, { quantity: 10, price: 6.99 }]
  },

  // --- CASH PRIZES (6 items) ---
  {
    id: 'c1',
    slug: '10k-tax-free-cash',
    title: '£10,000 Tax-Free Cash',
    description: 'The ultimate financial boost for your family. Pay off bills, book a holiday, or save for the future.',
    image: 'https://images.unsplash.com/photo-1554672723-b208dc2d7197?auto=format&fit=crop&q=80&w=1000',
    retailValueGBP: 10000,
    ticketPriceGBP: 4.99,
    maxTickets: 3000,
    ticketsSold: 2850,
    drawDateTime: addDays(0.5),
    category: 'Cash',
    status: 'ending_soon',
    bundles: [{ quantity: 1, price: 4.99 }, { quantity: 5, price: 19.99 }]
  },
  {
    id: 'c2',
    slug: '2k-monthly-bills',
    title: '£2,000 Monthly Bills Buster',
    description: 'Clear your household bills for months with this cash injection.',
    image: 'https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?auto=format&fit=crop&q=80&w=1000',
    retailValueGBP: 2000,
    ticketPriceGBP: 0.99,
    maxTickets: 2500,
    ticketsSold: 1200,
    drawDateTime: addDays(2),
    category: 'Cash',
    status: 'active',
    bundles: [{ quantity: 1, price: 0.99 }, { quantity: 10, price: 8.99 }]
  },
  {
    id: 'c3',
    slug: '500-flash-cash',
    title: '£500 Flash Cash Friday',
    description: 'Quick draw cash prize. Ends tonight!',
    image: 'https://images.unsplash.com/photo-1559589689-577aabd1db4f?auto=format&fit=crop&q=80&w=1000',
    retailValueGBP: 500,
    ticketPriceGBP: 1.49,
    maxTickets: 500,
    ticketsSold: 450,
    drawDateTime: addDays(0.1),
    category: 'Cash',
    status: 'ending_soon',
    instantWin: true,
    bundles: [{ quantity: 1, price: 1.49 }, { quantity: 3, price: 3.99 }]
  },
  {
    id: 'c4',
    slug: '50k-mortgage-buster',
    title: '£50,000 Mortgage Buster',
    description: 'Life changing money. Clear a chunk of your mortgage instantly.',
    image: 'https://images.unsplash.com/photo-1560518883-ce09059ee971?auto=format&fit=crop&q=80&w=1000',
    retailValueGBP: 50000,
    ticketPriceGBP: 9.99,
    maxTickets: 8000,
    ticketsSold: 200,
    drawDateTime: addDays(14),
    category: 'Cash',
    status: 'new',
    bundles: [{ quantity: 1, price: 9.99 }, { quantity: 3, price: 24.99 }]
  },
  {
    id: 'c5',
    slug: '1k-supermarket-sweep',
    title: '£1,000 Supermarket Voucher',
    description: 'Valid at Tesco, Sainsbury\'s, Asda or Waitrose. Feed the family for free.',
    image: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&q=80&w=1000',
    retailValueGBP: 1000,
    ticketPriceGBP: 0.79,
    maxTickets: 1500,
    ticketsSold: 100,
    drawDateTime: addDays(5),
    category: 'Cash',
    status: 'active',
    instantWin: true,
    bundles: [{ quantity: 1, price: 0.79 }, { quantity: 10, price: 6.99 }]
  },
  {
    id: 'c6',
    slug: '5k-emergency-fund',
    title: '£5,000 Emergency Fund',
    description: 'Build your safety net instantly with this tax-free cash prize.',
    image: 'https://images.unsplash.com/photo-1621981386829-9b416a40202b?auto=format&fit=crop&q=80&w=1000',
    retailValueGBP: 5000,
    ticketPriceGBP: 2.99,
    maxTickets: 2000,
    ticketsSold: 500,
    drawDateTime: addDays(4),
    category: 'Cash',
    status: 'active',
    bundles: [{ quantity: 1, price: 2.99 }, { quantity: 4, price: 10.00 }]
  }
];

export const winners: Winner[] = [
  {
    id: 'w1',
    name: 'Sarah J.',
    location: 'Manchester',
    prize: 'Bugaboo Fox 5',
    date: '2 Oct 2023',
    image: 'https://images.unsplash.com/photo-1544717297-fa95b6ee9643?auto=format&fit=crop&q=80&w=400',
    ticketNumber: 'BF-4921'
  },
  {
    id: 'w2',
    name: 'David M.',
    location: 'Essex',
    prize: '£2,000 Cash',
    date: '28 Sep 2023',
    image: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=400',
    ticketNumber: 'CH-9921'
  },
  {
    id: 'w3',
    name: 'Emma W.',
    location: 'Bristol',
    prize: 'Nursery Makeover',
    date: '15 Sep 2023',
    image: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&q=80&w=400',
    ticketNumber: 'NM-1022'
  },
  {
    id: 'w4',
    name: 'James P.',
    location: 'Leeds',
    prize: 'Disney Holiday',
    date: '10 Sep 2023',
    image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=400',
    ticketNumber: 'DH-5511'
  }
];